arrow_style: {
  stroke: "#545B64"
  stroke_width: "2"
  badge_bg: "#232F3E"
  badge_color: "#ffffff"
  badge_size: "38"
  badge_shape: "circle"
}

aws_cloud: AWS Cloud {
  pos: "20, 15, 1570, 830"
  stroke: "#545B64"
  header_icon: "aws cloud logo"

  customer_account: Customer's AWS Account {
    pos: "165, 90, 830, 720"
    stroke: "#545B64"
    header_icon: "aws account"

    auth: Authentication {
      pos: "200, 175, 285, 195"
      stroke: "#545B64"
      stroke_style: "dashed"

      cognito: Amazon Cognito {
        pos: "280, 295"
        icon: "cognito"
      }

      openid: OpenID\nConnect {
        pos: "410, 295"
        icon: "iam identity center"
      }
    }

    dynamodb: Amazon DynamoDB {
      pos: "590, 295"
      icon: "dynamodb"
    }

    step_functions: AWS Step Functions\nworkflow {
      pos: "665, 175, 310, 400"
      stroke: "#E7157B"
      header_icon: "step functions"

      lambda_sf: AWS Lambda {
        pos: "820, 320"
        icon: "lambda"
      }

      cf: AWS CloudFormation {
        pos: "820, 470"
        icon: "cloudformation"
      }
    }

    appsync: AWS AppSync {
      pos: "380, 460"
      icon: "appsync"
    }

    lambda: AWS Lambda {
      pos: "560, 460"
      icon: "lambda"
    }

    cloudfront: Amazon CloudFront {
      pos: "380, 670"
      icon: "cloudfront"
    }

    s3_customer: Amazon S3 {
      pos: "590, 670"
      icon: "s3"
    }

    fargate: AWS Fargate {
      pos: "820, 670"
      icon: "fargate"
    }
  }

  managed_account: AWS Managed Account {
    pos: "1060, 90, 510, 720"
    stroke: "#545B64"
    header_icon: "aws account"

    s3_repl: S3 replication\ncomponent template {
      pos: "1180, 250"
      icon: "cloudformation template"
      icon_color: "Orange"
    }

    ddb_repl: DynamoDB\nreplication\ncomponent template {
      pos: "1420, 250"
      icon: "cloudformation template"
      icon_color: "Orange"
    }

    s3_managed: Amazon S3 {
      pos: "1180, 460"
      icon: "s3"
    }

    ecr_repl: ECR replication\ncomponent template {
      pos: "1420, 460"
      icon: "cloudformation template"
      icon_color: "Orange"
    }

    ecr: Amazon ECR {
      pos: "1180, 670"
      icon: "ecr"
    }

    ecr_docker: ECR replication\nDocker image {
      pos: "1420, 670"
      icon: "ecr"
      icon_color: "Orange"
    }
  }

  dth_ui: Data Transfer\nHub UI {
    pos: "90, 560"
    icon: "client"
    icon_variant: "Light"
  }
}

user: User {
  pos: "90, 910"
  icon: "user"
  icon_variant: "Light"
  external: "true"
}

# Unlabeled connections
openid -> cognito
cloudfront -> s3_customer
cf -> fargate
user -> dth_ui

# Numbered flow
dth_ui -> cloudfront: 1 {
  waypoints: "90, 670"
  badge_pos: "250, 670"
}

dth_ui -> appsync: 2 {
  waypoints: "90, 460"
  badge_pos: "270, 460"
}

dth_ui -> cognito: 3 {
  waypoints: "90, 295"
  badge_pos: "90, 430"
}

appsync -> lambda: 4

lambda -> step_functions: 5 {
  border_stop: "step_functions.left"
  badge_pos: "630, 460"
}

s3_managed -> cf: 6 {
  badge_pos: "1030, 460"
}

ecr -> fargate: 7 {
  badge_pos: "1030, 670"
}

cognito -> dynamodb: 8 {
  badge_pos: "470, 260"
}
